name: Pull Docker Image
description: Pulls and caches a Docker image
inputs:
  context:
    description: The context of the Docker image to build (instead of pull)
    required: false
  image:
    description: The Docker image to pull
    required: true
  tag:
    description: The tag of the Docker image to pull
    required: false
    default: latest
  cache-key-suffix:
    description: Suffix to apply to the cache key (useful to force new cache creation)
    required: false
    default: v1
runs:
  using: composite
  steps:
    - run: mkdir -p ~/.images/${{ inputs.image }}
      shell: bash
    - id: image-cache
      uses: actions/cache@v3
      with:
          path: ~/.images/${{ inputs.image }}
          key: ${{ inputs.image }}-${{ inputs.tag }}-${{ inputs.cache-key-suffix }}
    - if: steps.image-cache.outputs.cache-hit != 'true'
      run: |
          [[ -n "${{ inputs.context }}" ]] && docker build -t ${{ inputs.image }}:${{ inputs.tag }} ${{ inputs.context }}
          [[ -z "${{ inputs.context }}" ]] && docker pull ${{ inputs.image }}:${{ inputs.tag }}
          docker save -o ~/.images/${{ inputs.image }}/${{ inputs.tag }}.tar ${{ inputs.image }}:${{ inputs.tag }}
      shell: bash
    - if: steps.image-cache.outputs.cache-hit == 'true'
      run: docker load -i ~/.images/${{ inputs.image }}/${{ inputs.tag }}.tar
      shell: bash
